# NOTE: Generate `../kobo-env/` environment files using
# https://github.com/kobotoolbox/kobo-install. You may manually customize the
# files afterwards and stop using kobo-install if necessary.
version: '3'

services:
  kobocat:
    image: kobotoolbox/kobocat:2.021.47
    hostname: kobocat
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/aws.txt
      - ../kobo-env/envfiles/external_services.txt
      - ../kobo-env/envfiles/kobocat.txt
      - ../kobo-env/envfiles/nginx.txt
      - ../kobo-env/envfiles/smtp.txt
    sysctls:
      - net.core.somaxconn=2048
    environment:
      - ENKETO_PROTOCOL=https
      - KPI_PORT=8000
      - KC_UWSGI_MAX_REQUESTS=512
      - KC_UWSGI_WORKERS_COUNT=2
      - KC_UWSGI_CHEAPER_RSS_LIMIT_SOFT=134217728
      - KC_UWSGI_CHEAPER_WORKERS_COUNT=1
      - KC_UWSGI_HARAKIRI=120
      - KC_UWSGI_WORKER_RELOAD_MERCY=120
    volumes:
      - ./.vols/static/kobocat:/srv/static
      - ./.vols/kobocat_media_uploads:/srv/src/kobocat/media
      - ./backups/kobocat:/srv/backups
      - ./log/kobocat:/srv/logs
      - ./scripts/wait_for_mongo.bash:/srv/init/wait_for_mongo.bash:ro
      - ./scripts/wait_for_postgres.bash:/srv/init/wait_for_postgres.bash:ro
      - ./scripts/runtime_variables_kobocat.source.bash:/etc/profile.d/runtime_variables_kobocat.source.bash.sh:ro
      - ./uwsgi/kc_uwsgi.ini:/srv/src/kobocat/docker/kobocat.ini
    restart: always
    networks:
      kobo-fe-network:
        aliases:
          - kobocat
          - kobocat.docker.container
          - kobocat.internal

  kpi:
    image: kobotoolbox/kpi:2.021.47
    hostname: kpi
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/aws.txt
      - ../kobo-env/envfiles/external_services.txt
      - ../kobo-env/envfiles/kpi.txt
      - ../kobo-env/envfiles/nginx.txt
      - ../kobo-env/envfiles/smtp.txt
    sysctls:
      - net.core.somaxconn=2048
    environment:
      - SYNC_KOBOCAT_XFORMS=False # Should be True on at least one frontend environment
      - KPI_UWSGI_MAX_REQUESTS=512
      - KPI_UWSGI_WORKERS_COUNT=2
      - KPI_UWSGI_CHEAPER_RSS_LIMIT_SOFT=134217728
      - KPI_UWSGI_CHEAPER_WORKERS_COUNT=1
      - KPI_UWSGI_HARAKIRI=120
      - KPI_UWSGI_WORKER_RELOAD_MERCY=120
    volumes:
      - ./.vols/static/kpi:/srv/static
      - ./log/kpi:/srv/logs
      - ./scripts/wait_for_mongo.bash:/srv/init/wait_for_mongo.bash:ro
      - ./scripts/wait_for_postgres.bash:/srv/init/wait_for_postgres.bash:ro
      - ./scripts/runtime_variables_kpi.source.bash:/etc/profile.d/runtime_variables_kpi.source.bash.sh:ro
      - ./uwsgi/kpi_uwsgi.ini:/srv/src/kpi/uwsgi.ini
      # Persistent storage for FileFields when S3 not used (e.g. exports, uploaded map layers)
      - ./.vols/kpi_media:/srv/src/kpi/media
      # Allow access to KoBoCAT media uploads within KPI
      - ./.vols/kobocat_media_uploads:/srv/src/kobocat/media
    restart: always
    networks:
      kobo-fe-network:
        aliases:
          - kpi
          - kpi.docker.container
          - kpi.internal

  nginx:
    image: nginx:1.20
    hostname: nginx
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/nginx.txt
      - ../kobo-env/envfiles/kobocat.txt
      - ../kobo-env/envfiles/kpi.txt
    environment:
      - UWSGI_PASS_TIMEOUT=130
      - TEMPLATED_VAR_REFS=$${PUBLIC_REQUEST_SCHEME} $${INTERNAL_DOMAIN_NAME} $${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}
    volumes:
        - ./.vols/static:/srv/www:ro
        - ./log/nginx:/var/log/nginx
        - ./.vols/kobocat_media_uploads:/media
        - ./.vols/kpi_media/__public:/srv/kpi_media/__public:ro
        - ./nginx/docker-entrypoint.d/30-init-kobo-nginx.sh:/docker-entrypoint.d/30-init-kobo-nginx.sh
        - ./nginx/kobo-docker-scripts/:/kobo-docker-scripts
    restart: always
    networks:
      kobo-fe-network:
        aliases:
          - nginx
          - nginx.internal

  enketo_express:
    image: kobotoolbox/enketo-express-extra-widgets:2.8.1
    env_file:
      - ../kobo-env/envfile.txt
    environment:
      - ENKETO_BUILD_IE11=true
    restart: always
    volumes:
      - ../kobo-env/enketo_express/config.json:/srv/src/enketo_express/config/config.json
      # Override Enketo Express icons.
      - ./enketo_express/favicon.ico:/srv/src/enketo_express/public/images/favicon.ico:ro
      - ./enketo_express/icon_180x180.png:/srv/src/enketo_express/public/images/icon_180x180.png:ro
      - ./.vols/enketo_express/checksum:/srv/src/enketo_express/checksum
      - ./.vols/enketo_express/build/css:/srv/src/enketo_express/public/css
      - ./.vols/enketo_express/build/js:/srv/src/enketo_express/public/js/build
      - ./.vols/enketo_express/build/locales:/srv/src/enketo_express/locales/build
    networks:
      kobo-fe-network:
        aliases:
          - enketo_express
          - enketo_express.internal

networks:
  kobo-fe-network:
    driver: bridge
